[package]
name = "hftbacktest"
version = "0.5.0"
edition = "2021"
authors = ["nkaz001 <nkaz001@protonmail.com>"]
license = "MIT"
documentation = "https://docs.rs/hftbacktest/"
repository = "https://github.com/nkaz001/hftbacktest/"
readme = "README.md"
description = "A high-frequency trading and market-making backtesting tool accounts for limit orders, queue positions, and latencies, utilizing full tick data for trades and order books."
keywords = [
    "quantitative",
    "trading",
    "backtesting",
    "cryptocurrency",
    "hft"
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
rust-version = "1.82"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["backtest", "live"]
backtest = ["zip", "uuid", "nom", "hftbacktest-derive"]
live = ["chrono", "tokio", "futures-util", "iceoryx2", "rand", "toml", "serde"]
unstable_fuse = []

[dependencies]
tracing = "0.1.40"
anyhow = "1.0.79"
thiserror = "2.0.3"
dyn-clone = "1.0.17"
bincode = "2.0.0-rc.3"
chrono = { version = "0.4.33", optional = true }
tokio = { version = "1.35.1", features = ["full"], optional = true }
zip = { version = "2.1.3", optional = true }
futures-util = { version = "0.3.30", optional = true }
rand = { version = "0.8.5", optional = true }
uuid = { version = "1.8.0", features = ["v4"], optional = true }
nom = { version = "7.1.3", optional = true }
iceoryx2 = { version = "0.4.1", optional = true, features = ["logger_tracing"] }
serde = { version = "1.0.215", optional = true, features = ["derive"] }
toml = { version = "0.8.19", optional = true }
hftbacktest-derive = { path = "../hftbacktest-derive", optional = true, version = "0.2.0" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = [] }
clap = { version = "4.5.4", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]