[package]
name = "hftbacktest"
version = "0.3.1"
edition = "2021"
authors = ["nkaz001 <nkaz001@protonmail.com>"]
license = "MIT"
documentation = "https://docs.rs/hftbacktest/"
repository = "https://github.com/nkaz001/hftbacktest/"
readme = "README.md"
description = "A high-frequency trading and market-making backtesting tool accounts for limit orders, queue positions, and latencies, utilizing full tick data for trades and order books."
keywords = [
    "quantitative",
    "trading",
    "backtesting",
    "cryptocurrency",
    "hft"
]
categories = ["finance", "mathematics", "science", "algorithms", "simulation"]
rust-version = "1.79"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["backtest", "live", "binancefutures", "bybit"]
backtest = ["zip", "uuid", "nom", "hftbacktest-derive"]
live = ["chrono", "tokio", "futures-util"]
use_reqwest = ["reqwest"]
binancefutures = ["serde", "serde_json", "tokio-tungstenite", "use_reqwest", "sha2", "hmac", "rand"]
bybit = ["serde", "serde_json", "tokio-tungstenite", "use_reqwest", "sha2", "hmac", "rand"]
unstable_l3 = []
unstable_fuse = []

[dependencies]
tracing = "0.1.40"
anyhow = "1.0.79"
thiserror = "1.0.57"
dyn-clone = "1.0.17"
chrono = { version = "0.4.33", optional = true }
serde = { version = "1.0.196", features = ["derive"], optional = true }
serde_json = { version = "1.0.113", optional = true }
tokio = { version = "1.35.1", features = ["full"], optional = true }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"], optional = true }
reqwest = { version = "0.12.3", features = ["json"], optional = true }
zip = { version = "2.1.3", optional = true }
futures-util = { version = "0.3.30", optional = true }
sha2 = { version = "0.11.0-pre.3", optional = true }
hmac = { version = "0.13.0-pre.3", optional = true }
rand = { version = "0.8.5", optional = true }
uuid = { version = "1.8.0", features = ["v4"], optional = true }
nom = { version = "7.1.3", optional = true }
hftbacktest-derive = { path = "../hftbacktest-derive", optional = true, version = "0.1.0" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = [] }
clap = { version = "4.5.4", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]